# Corrected for macOS compatibility
name: omni
channels:
  - pytorch
  - conda-forge
  - pyg
dependencies:
  - python=3.10
  - pytorch::pytorch=2.2.0
  - numpy<2.0.0
  - tensorboard
  - pip
  - git
  - gitpython
  - ca-certificates
  - certifi
  - openssl
  - parameterized
  - setuptools
  - cmake
  - make
  - ninja
  - ipython
  - jupyterlab
  - matplotlib
  - seaborn
  - tqdm
  - sparsehash
  - sphinx>=7.0.0
  - sphinx_rtd_theme
  - myst-parser
  - pandas
  - rich
  - pytest-benchmark
  - pytorch-lightning=1.9.4
  - omegaconf
  - flatten-dict
  - wandb
  - pyvips
  - pip:
    - opencv-python==4.7.0.72
    - opencv-python-headless==4.7.0.72
    - pytorch_msssim
    - jupyter
    - torchvision==0.17.0
    - linkify-it-py
    - python-pycg
    - torch_sparse
    - point_cloud_utils==0.29.5
    - loguru
    - einops
    - dask
    - timm
    - pynvml
    - transformers
    - polyscope
    - trimesh
    - spatialdata[extra]
    - scanpy
    - squidpy
    - pyvista
    - geopandas
    - rasterio
    - pykan==0.2.3
    - hnswlib
    - annoy
    - "scanpy[louvain]"
    - leidenalg
    - cellpose
    - faiss-cpu